version: '3'

services:
  app:
    image: nome-da-imagem:staging   
    container_name: saudeinteligente_app_staging
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - saudeinteligente_staging_network

  db:
    image: postgres:latest
    container_name: saudeinteligente_db_staging
    environment:
      - POSTGRES_DB=saudeinteligente
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    volumes:
      - saudeinteligente_db_staging_data:/var/lib/postgresql/data
    networks:
      - saudeinteligente_staging_network

networks:
  saudeinteligente_staging_network:

volumes:
  saudeinteligente_db_staging_data:
