name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven (Debug Mode)
      run: mvn clean install -DskipTests -e -X

  deploy_staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging..."
        docker-compose -f docker-compose.yml up -d

  deploy_production:
    needs: deploy_staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/v*'

    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        docker-compose -f docker-compose.yml up -d

